services:
  db:
    image: postgres:16
    container_name: pg-dev
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PGPORT}:5432"
    # Use a named volume for fewer Windows/WSL permission headaches
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Optional: throwaway, single-file DB GUI
  adminer:
    image: adminer:latest
    container_name: pg-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
